[package]
name = "audio-thing"
version = "0.1.0"
authors = ["polyfloyd <floyd@polyfloyd.net>"]
publish = false

[profile.dev]
opt-level = 3

[features]
unstable = []

[dependencies]
badlog = "^0.2.5"
byteorder = "^1.0.0"
derive-error = "^0.0.3"
dft = "^0.5.4"
id3 = { rev = "0be2f40a", git = "https://github.com/jameshurst/rust-id3" }
lazy_static = "^0.2.8"
log = "^0.3.7"
notify = "^4.0.1"
rand = "^0.3.15"
regex = "^0.2.1"
rusqlite = { version = "^0.11.0", features = [ "functions" ] }
sample = "^0.6.2"
xdg = "^2.1.0"
libflac_sys = { path = "libflac_sys" }
liblame_sys = { path = "liblame_sys" }
libpulse_sys = { path = "libpulse_sys" }
