[package]
name = "audio-thing"
version = "0.1.0"
authors = ["polyfloyd <floyd@polyfloyd.net>"]

[dependencies]
badlog = "*"
byteorder = "*"
dft = "*"
id3 = "*"
lazy_static = "*"
log = "*"
regex = "*"
sample = "*"
libflac_sys = { version = "^1.3.2", path = "libflac_sys" }
libpulse_sys = { version = "^10.0.0", path = "libpulse_sys" }
