[package]
name = "audio-thing"
version = "0.1.0"
authors = ["polyfloyd <floyd@polyfloyd.net>"]
build = "build.rs"

[dependencies]
dft = "*"
flac = "*"
sample = "*"

[build-dependencies]
bindgen = "~0.20"
