[package]
name = "audio-thing"
version = "0.1.0"
authors = ["polyfloyd <floyd@polyfloyd.net>"]

[dependencies]
badlog = "*"
byteorder = "*"
dft = "*"
id3 = { version = "*", git = "https://github.com/polyfloyd/rust-id3" }
lazy_static = "*"
log = "*"
notify = "*"
regex = "*"
rusqlite = { version = "*", features = [ "functions" ] }
sample = "*"
xdg = "*"
libflac_sys = { version = "^1.3.2", path = "libflac_sys" }
liblame_sys = { version = "^3.99.0", path = "liblame_sys" }
libpulse_sys = { version = "^10.0.0", path = "libpulse_sys" }
